[pytest]
DJANGO_SETTINGS_MODULE = portfolio_project.settings
python_files = tests.py test_*.py *_tests.py
python_classes = *Test
python_functions = test_*
addopts = -v --tb=short

[coverage:run]
source = core
omit =
    */migrations/*
    */tests.py
    manage.py

[coverage:report]
show_missing = True
skip_covered = False
