# Generated by Django 5.0.4 on 2026-04-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("excerpt", models.CharField(max_length=500, verbose_name="Extrait")),
                (
                    "content",
                    models.TextField(verbose_name="Contenu (HTML ou Markdown)"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Tags (virgule-séparés)",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Publié"), ("draft", "Brouillon")],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Courriel")),
                ("subject", models.CharField(max_length=300, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("read", "Lu"),
                            ("replied", "Répondu"),
                            ("archived", "Archivé"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("powerbi", "Power BI"),
                            ("sql", "SQL / Data Modeling"),
                            ("python", "Python / ETL"),
                            ("ml", "Machine Learning"),
                            ("dashboard", "Dashboard"),
                            ("other", "Autre"),
                        ],
                        default="powerbi",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="Description courte"),
                ),
                (
                    "long_description",
                    models.TextField(blank=True, verbose_name="Description détaillée"),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Ex: Power BI, DAX, SQL Server, Python",
                        max_length=500,
                        verbose_name="Technologies (virgule-séparées)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/thumbnails/",
                        verbose_name="Miniature",
                    ),
                ),
                (
                    "live_url",
                    models.URLField(blank=True, verbose_name="URL Démonstration"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="URL GitHub")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Projet vedette"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publié"),
                            ("draft", "Brouillon"),
                            ("archived", "Archivé"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Classe CSS ou identifiant SVG icon",
                        max_length=100,
                        verbose_name="Icône CSS/SVG class",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Catégorie de compétence",
                "verbose_name_plural": "Catégories de compétences",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Débutant"),
                            (2, "Intermédiaire"),
                            (3, "Avancé"),
                            (4, "Expert"),
                            (5, "Maître"),
                        ],
                        default=3,
                        verbose_name="Niveau (1-5)",
                    ),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        default=80, verbose_name="Pourcentage (0-100)"
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(blank=True, max_length=100, verbose_name="Icône"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "ordering": ["category__order", "order"],
            },
        ),
    ]
